In [1]:
import numpy as np

#creating an array in numpy

print("\ncreating 1D array")
a1 = np.array([1,2,3])
print(a1)
print(a1.shape)
print("dimension", a1.ndim)

print("\ncreating 2D array")
a2 = np.array([[1,2], [3,4]])
print(a2)
print(a2.shape)
print("dimension", a2.ndim)

print("\ncreating 3D array")
a3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(a3)
print(a3.shape)
print("dimension", a3.ndim)


creating 1D array
[1 2 3]
(3,)
dimension 1

creating 2D array
[[1 2]
 [3 4]]
(2, 2)
dimension 2

creating 3D array
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
dimension 3


In [2]:
# indexing

print(a1[2])
print(a2[1,1])
print(a3[1,0,1])

print(np.array([1,2,3], ndmin=2)) #make one dim array to two dim

print(a1**2)

3
4
6
[[1 2 3]]
[1 4 9]


In [4]:
#Data type

a = np.array([1,2,3,4])
print(a.dtype)
a = a.reshape(2,2)
print(a)
print('modified array dim', a.ndim)
print(a.dtype)
print(a.itemsize)

print('changing dtype')
a = np.array(a, dtype=np.float64)
print(a)
print(a.dtype)

int64
[[1 2]
 [3 4]]
modified array dim 2
int64
8
changing dtype
[[1. 2.]
 [3. 4.]]
float64


In [5]:
print("complex type")
a = np.array(a, dtype=np.complex_)
print(a)

complex type
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [6]:
a.ravel() #make n dim to one dim array

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [8]:
# Mathematical function
a = np.arange(0,21,2)
print('minimum =', a.min(), 'maximum =', a.max())
print('sum =', a.sum())
print(np.sqrt(a))
print(np.mean(a))
print(np.std(np.array([1,2,3,4])))

minimum = 0 maximum = 20
sum = 110
[0.         1.41421356 2.         2.44948974 2.82842712 3.16227766
 3.46410162 3.74165739 4.         4.24264069 4.47213595]
10.0
1.118033988749895


In [9]:
a = np.arange(1,21,2).reshape(2,5)
print(a)
b = np.arange(2,21,2).reshape(2,5)
print(b)
print('Multiplication')
print(a*b)
print('Matrix multiplication')
print(a)
print(b.reshape(5,2))
print(a.dot(b.reshape(5,2)))

[[ 1  3  5  7  9]
 [11 13 15 17 19]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
Multiplication
[[  2  12  30  56  90]
 [132 182 240 306 380]]
Matrix multiplication
[[ 1  3  5  7  9]
 [11 13 15 17 19]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
[[330 380]
 [830 980]]


In [10]:
a = np.arange(1,10).reshape(3,3)
print(a)
print(a[:,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]
 [8]]


In [11]:
'''
    numpy array stores numbers list different from python list.
    python list stores numbers as object where numpy array stores as interger.
    python list one number store 10byte more than np array.
    python list stores in linked list format where numpy stores numbers in continuous memory.
'''

size = 100000

l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

import time

start = time.time()
result =  [(z+y) for z,y in zip(l1,l2)]
print("the execution time normal array is:", (time.time()-start)*1000)

start = time.time()
result = a1 + a2
print("the execution time numpy array is:", (time.time()-start)*1000)

the execution time normal array is: 19.057035446166992
the execution time numpy array is: 1.607656478881836
